sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
    - depends/built
    - depends/work
    - depends/sdk-sources
    - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j4
    - RUN_UNIT_TESTS=false
    - RUN_FUNCTIONAL_TESTS=false
    - RUN_BENCH=false  # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=1000M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - DOCKER_PACKAGES="zip build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
  matrix:
# WINDOWS
      - HOST=x86_64-w64-mingw32 DOCKER_NAME_TAG=ubuntu:18.04 HOST=x86_64-w64-mingw32 PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine-binfmt wine64" BITCOIN_CONFIG="--enable-reduce-exports"
# LINUX trusty
      - HOST=x86_64-unknown-linux-gnu DOCKER_NAME_TAG=ubuntu:14.04 HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq" GOAL="install" BITCOIN_CONFIG="--with-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
# LINUX xenial
      - HOST=x86_64-unknown-linux-gnu DOCKER_NAME_TAG=ubuntu:16.04 HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq" GOAL="install" BITCOIN_CONFIG="--with-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
# LINUX bionic
      - HOST=x86_64-pc-linux-gnu DOCKER_NAME_TAG=ubuntu:18.04 PACKAGES="python3-zmq" GOAL="install" BITCOIN_CONFIG="--with-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
# OSX
      - HOST=x86_64-apple-darwin16 DOCKER_NAME_TAG=ubuntu:18.04 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools" OSX_SDK=10.11 BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror"
before_install:
  - set -o errexit; source .travis/test_03_before_install.sh
install:
  - set -o errexit; source .travis/test_04_install.sh
before_script:
  - set -o errexit; source .travis/test_05_before_script.sh
script:
  - set -o errexit; source .travis/test_06_script.sh
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
before_deploy:
    - sudo chown -R travis:travis /home/travis/
    - "cd $TRAVIS_BUILD_DIR"
    - "chmod +x .travis/test_07_deploy.sh"    
    - "./.travis/test_07_deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: SYICPHjp2flxh5oXBWwaSfQY32x1QnroEL0dKais5/bGv0kIY2NQDvVRifuxrRKJ2rAwJ9qnUK63+7ikTPGe8xsWlhiVFpR8cGKgl0LI+kw0hVVwOwa84TNo3/0wtiUd20gjeYiBRbTUlRrPEbtvE5MJQQ+yfZ0AEymVIUPRsQuO4NC3AeTtiWad1F8n9SsEg7V7EmKSY3jYITfJoiwoepFf/IkWbtpRraWz6FwY7qhOhXs5na2cMyui9pt0lzEDv8jS31huxvVIf9sCCn4f5snq+Tl0P2PvSN/qy0y32lGnCY/443JQ22oHnpmwLUxsoVTJxwhn6l1Oi/xaRyD4aauxUVhEkBOED3CNM2Yr2WooKTt3jfwdOv+nJZtyoTfeyWU5tIE70IRBBmbtZTX654K5yLVIybE2rbdJF59tFEhiClOx1elOqsx+HDS9pgwL3bHI9u0Sr8hARgIfgXITgKVpUjvkh6T0Ewn5IF5tfi1vvGXN1XzVzfkIFiDPki51yeXQZhQ4KApZsyLgDoU3SArnw3+xBqBUsWaA9vfrFgUlPgcWpBcXBIulv8P1VZA+MZUCa21rfj6+5lA47PblMTZ+ytBxLsAsx/GrEBZbKgFsYOjYYrbnRgrfjgv84cL7C9ihp/vXbEWoB0VyX4Kjyrp4Q9urLGu4QlQnWKd4Bec=
  file_glob: true
  file:
    - out/**/zip/*
  skip_cleanup: true
  on:
    tags: true
